### ISSUE TITLE
Ability to define securityContext for init containers

### ISSUE THREAD

**Issue by jusabatier** [area-42/helm-charts#1]
Is it possible to allow to define securityContext for init containers in the value.yaml file ?

It's usefull when using Istio as ingress, because we need to set : 

```
securityContext:
        runAsUser: 1337
```

To enable init containers to access network when the istio sidecar is injected.

**Comment by ChaosKid42** [comment]
Please check if today's release works for you.

**Comment by jusabatier** [comment]
It works well. Thanks for your reactivity !

**Comment by ChaosKid42** [comment]
No Problem. Glad to help.
